algoritmo "Algoritmo que faça a soma de dois números"
// Disciplina: LOPAL (Lógica de programação)


//F9 executa o código

// Autor: Vitor Rodrigues Santos
// Data : 07/04/2026

var
//Definindo as variáveis

n1, n2, resultado: real

inicio
// Entrada dos dados

   escreva("Digite o primeiro número da soma: ")
   leia(n1)
   
   escreva("Digite o segundo número para soma: ")
   leia(n2)
   
// O calculo será feito utilizando a fórmula abaixo

   resultado <- n1 + n2
   
   limpatela
   
// Vai exibir os dados abaixo
   escreval("O resultado da soma de ", n1, " +", n2, " será ", resultado)
fimalgoritmo
